### ISSUE TITLE
End to End Testing with Google's Puppeteer

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#100]
https://egghead.io/courses/end-to-end-testing-with-google-s-puppeteer
In this course we will create common application features and run multiple different types of tests against them. This includes rendering the content and measuring the overall performance, automating tests, and mimicking user activity.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/gdws94ay1kz5urt/AACxKq4yX0IStWjEhEGRaBmEa?dl=0
