### ISSUE TITLE
Optimize User Experience for mobile devices and browsers

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#101]
https://egghead.io/courses/optimize-user-experience-for-mobile-devices-and-browsers

A lot of the time, web apps are built primarily with the desktop layout in consideration, and the mobile layout suffers as a result. In this course we are going to discuss using features of user interface which are optimised for mobile devices.

We are going to discuss CSS features that make a big difference and build entire components that work great on mobile devices and browsers. We are going to take into account browser support to ensure our users are getting the experience we want them to.

More and more of our users depend on their mobile device to use our web apps. With this in mind, we are going to look at how to optimise the components we build for smaller viewports, and how to ensure our customer gets an optimised version of our web app for their device.

We are going to discuss different ways we can view, test, and debug our web app in a mobile setting so that we know what we are seeing is what our user is seeing, because sometimes a desktop browser emulating a mobile device just isn’t enough.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/zfcq5p6v5k3t76w/AAA7p5ms-5xKstvVdigi-8k7a?dl=0
