### ISSUE TITLE
React Native Navigation for Mobile Applications

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#102]
https://egghead.io/courses/react-native-navigation-for-mobile-applications

React Navigation makes the easy things easy and the hard things possible. This course will help you understand how to customize and use React Navigation for more complex navigation patterns.

To succeed in this course you’ll want a basic understanding of the React Navigation API and how to use the default navigators.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/bhlvu52gssvreko/AAB8-1lzE8zxgOAx6xEVuyHDa?dl=0
