### ISSUE TITLE
Create a Progressive Web App from a Single Page Application

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#103]
https://egghead.io/courses/create-a-progressive-web-app-from-a-single-page-application

In this course I’m gonna show you how to take an existing SPA made in Vue.js based on the Webpack template of vue-cli, and pragmatically convert it to a PWA

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/33zx0rthlf3u699/AABqq-Dv6167iQ3lI_AiHqI0a?dl=0
