### ISSUE TITLE
End to End testing with Cypress

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#106]
https://egghead.io/courses/end-to-end-testing-with-cypress

The tools available for unit testing have come a long way. While testing may never be “easy”, the available tools have certainly moved testing closer to the simple end of the spectrum. Full end to end testing hasn’t quite kept the same pace and as a result many applications are testing manually and often by users in production. Cypress provides a testing environment that makes end-to-end testing fast and reliable with a simple API that makes creating automated unit tests for your web applications a no-brainer.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/rp6voomlfolbyl7/AABpvcBbHlkE9vfiZi3idsVCa?dl=0
