### ISSUE TITLE
Functional Programming Concepts in Purescript

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#107]
https://egghead.io/courses/functional-programming-concepts-in-purescript

In this course we will use http://try.purescript.org/ to show basics into PureScript with an instant visual representation, investigate the type system and ways to reason about common programing problems with PureScript. We will go through plenty of functional programming concepts as PureScript is a purely functional language.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/lnbilhup8olx1q1/AAAi3kZVwNgMzUxTuBdJJKMja?dl=0
