### ISSUE TITLE
Get Started with Reason

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#111]
This course will not only teach you the basics you need to write your first Reason program, but also show how to leverage features of functional programming languages like variant types and pattern matching. After you gained some knowledge about the basics the course will dig even further into the language and end with some basics on how to use BuckleScript.https://egghead.io/courses/get-started-with-reason

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/l3x7wcwbc1zolk0/AAA9zyjCtAlKF-gOoaM8iJA7a?dl=0
