### ISSUE TITLE
Integrate IBM Domino with NodeJS

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#114]
## Primary Tag
[Node.js](https://egghead.io/browse/libraries/node)

## Secondary Tag
[Express](https://egghead.io/browse/libraries/express), [JWT](https://egghead.io/browse/tools/jwt)

## Key Words
Authentication, Server, Proxy, JSON Web Tokens (JWT)

https://egghead.io/courses/integrate-ibm-domino-with-nodejs

The course will concentrate on Security initially as a lot of organizations use the Domino directory as the authentication provider. It will show how to authenticate to a NodeJS application using Domino, how to pass the security token through the NodeJS server to get Domino Data, how to capture the Domino login and then do a cross-domain call.

We will then cover using NodeJS / Express to get Domino Data and then show how to manipulate it server side using middleware before returning it back to the browser.

Finally, we will show how to reuse HTML which has been generated by Domino, this will be done by using Cheerio to scrape the Domino pages and then manipulating/saving them as handlebars templates.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/nro13vyqn72l2q0/AABO9KOflCbCJabxfevryaI8a?dl=0
