### ISSUE TITLE
Build GraphQL APIs with Node.js on MongoDB

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#115]
## Primary Tag
[GraphQL](https://egghead.io/browse/tools/graphql)

## Secondary Tag(s)
[Node.js](https://egghead.io/browse/libraries/node), [MongoDB](https://egghead.io/browse/platforms/mongodb), [Mongoose](https://egghead.io/browse/libraries/mongoose)

## Key Terms
API, Server, Query, CRUD (Create, Read, Update, Delete)

https://egghead.io/courses/build-graphql-apis-with-node-js-on-mongodb

In this course, we will build APIs with GraphQL, Node.Js, and Mongoose. You will learn how to setup the GraphQL server with NodeJs and ExpressJs. You will learn how to design GraphQL APIs in a real-world situation. We are going to build API to store products. You will learn how to create, update and delete a product by using GraphQL Mutations. I will show you how to load or get all the records from MongoDB by using GraphQL Queries.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/kso3l8g7zvvm7zg/AAAMWXN2MXXMYG0aF3meI99Va?dl=0
