### ISSUE TITLE
Reduce Redux Boilerplate with Redux-Actions

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#116]
## Primary Tag
[Redux](https://egghead.io/browse/libraries/redux)

## Secondary Tag
[React](https://egghead.io/browse/frameworks/react)

## Key Terms
Reduce, Boilerplate, Refactor, State Management, 

https://egghead.io/courses/reduce-redux-boilerplate-with-redux-actions

Redux is a powerful way to manage application state, but that power can come with a lot of code. A single update can sometimes require changes to many files and the code required to define action creators and to handle those actions in your reducer can start to get pretty repetitive.

The redux-actions library offers a small but powerful API to help cut down on some of the boilerplate that is typical of an application that uses Redux to handle state management.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/406mswwluols0gd/AABf5NJ6pTGJoJnM-SXxgJXVa?dl=0
