### ISSUE TITLE
JSON Web Token (JWT) Authentication with Node.js

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#118]
## Primary Tag
JWT

## Secondary Tags
Node.js

## Key Terms
Authentication, token issuer

https://egghead.io/courses/json-web-token-jwt-authentication-with-node-js

In this course, we will build a simple authentication server that will act as a token issuer, and we will use those tokens to access resources on an API. Starting from scratch, the participants will learn how easy token based authentication can be and will understand how to use them on their APIs as well as on the front end of their web applications.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/8mjt5ozsbg7fg28/AABTxaAIa29xxnHL1phGdU_3a?dl=0
