### ISSUE TITLE
Build GraphQL APIs with AWS AppSync

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#120]
## Primary tag
GraphQL

## Secondary tag
AWS

https://egghead.io/courses/build-graphql-apis-with-aws-appsync

Building a real world, scalable & production-ready GraphQL API is hard. In this course, we’ll learn how to create a production-ready GraphQL API that can handle everything from queries to mutations & subscriptions. We’ll also connect to our API from a React application and execute queries, mutations & subscriptions using the new API.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/jx0nmj96bsxrmp5/AADkO_ACeWihrqPYf2L9FjA6a?dl=0
