### ISSUE TITLE
Style and Theme Ionic Applications

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#121]
## Primary Tag
Ionic

https://egghead.io/courses/style-and-theme-ionic-applications

Theming Ionic applications is a topic that is often left undiscussed. This course will show you how Ionic’s theming system works so that your application can have its unique look. It will explore the built-in utilities, which you can leverage directly.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/ynt5l6sgkzxdsu8/AAAgsiTXWccw_8mfG1uEhTHia?dl=0
