### ISSUE TITLE
Automate Daily Tasks with Bash

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#122]
## Primary Tag
Bash

https://egghead.io/courses/automate-daily-tasks-with-bash

Whether it’s for npm install or some git commands, most front-end devs have used bash sometime. Bash has been around awhile (first released in 1989, so it’s as old as I am …and Taylor Swift) and it’s proven to be very efficient at automating tasks. Plus, bash is available on every commonly used operating system—it comes with macOS, is the default shell for many Linux distros, and is available on Windows via an emulator or the new Linux subsystem.

In this course, we’ll learn the essentials of what every front-end developer should know about bash. The topics we cover will give you confidence in doing things like creating build scripts that run on continuous integration servers or quickly testing and debugging an API with curl. We’ll go over:

- Interacting with the file system
- Creating, moving, copying, and deleting files and folders
- Finding files and text patterns in files
- Creating and running scripts
- Language syntax like variables, conditionals, and loops

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/wiq9s733x2da6be/AADBJPU1YC0Gl9k2wBfJqfuEa?dl=0
