### ISSUE TITLE
Convert SCSS (Sass) to CSS-in-JS

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#123]
## Primary Tag
CSS

## Secondary Tag
SCSS

https://egghead.io/courses/convert-scss-sass-to-css-in-js

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/28f4ml3w3pwcppw/AADT-TCdrXcqJ9QMPYhfe4Y8a?dl=0
