### ISSUE TITLE
Beautiful and Accessible Drag and Drop with react-beautiful-dnd

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#124]
# Primary Tag
react-beautiful-dnd

## Secondary Tags
React

react-beautiful-dnd enables beautiful and accessible drag and drop experiences for lists with React. In this course we will create a highly interactive task management application from scratch. You will be introduced to the building blocks of react-beautiful-dnd and you will learn how to use these building blocks to add powerful drag and drop experiences to your own projects.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/xwstpif1ftqy853/AABSS5skIppHvHB_AE_GQbIma?dl=0
