### ISSUE TITLE
Develop a Serverless Backend using Node.js on AWS Lambda

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#125]
## Primary Tags
AWS, Node.js

## Secondary Tags
Serverless

https://egghead.io/courses/develop-a-serverless-backend-using-node-js-on-aws-lambda

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/fv65er079ct52pi/AADfuGGbQADdVuDgmTQzEFPja?dl=0
