### ISSUE TITLE
Understanding JavaScript's Prototypal Inheritance

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#129]
## primary tag
JavaScript

https://egghead.io/courses/understanding-javascript-s-prototypal-inheritance

Prototypes within JavaScript can be a scary thought. If you come from a classical background, it may be difficult to understand how they are used and may want to manipulate prototypes to work like traditional classes. In this course, we’ll see how prototypes work as chained references to other objects. The topic of Prototypes includes how polymorphism and factory functions can be used within JavaScript. Some of the concepts involving inheritance in JavaScript is understanding and using the class, new, and this keyword. These combined with functions and objects provide the knowledge needed to use inheritance in code.

There are many tools built in that make using and debugging prototypes easier. We’ll explore using the instanceof, Object.create, and Object.getPrototypeOf functions to explain why objects have the properties that they do.

**Comment by MaggieAppleton** [comment]
Assigned to freelancer – Aleksander

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/0d840103dirf06k/AADwP5Tr_QGn2nYosIwYINNka?dl=0
