### ISSUE TITLE
Design Systems with React and Typescript in Storybook

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#132]
# Primary Tag
Storybook

# Secondary Tags
 React, TypeScript

https://egghead.io/courses/design-systems-with-react-and-typescript-in-storybook

In this course, we will learn how to set up all the necessary infrastructure to build a Design System of reusable React components, with state of the art developer experience afforded by Typescript and Storybook.

A design system is a series of components that can be reused in different combinations. Design systems allow you to manage design at scale. Design Systems can be a significant productivity multiplier in any medium-to-large project or company because you can document your components as you develop them, ensure a consistent look and feel throughout all your screens, and have a seamless workflow between designers and developers.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/2yui6bgq1w88bgx/AADacR9PsbfrUr-RoKq4IjZja?dl=0
