### ISSUE TITLE
Advanced Angular Component Patterns

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#133]
# Primary Tag
Angular

https://egghead.io/courses/advanced-angular-component-patterns

Components are all about encapsulating decisions. The perfect component is one that makes all the decisions the way you want without making you think about it. Unfortunately, no one knows ahead of time what decisions you’re going to want, so to make components reusable we try to set reasonable defaults and then allow you to override them when you don’t like the decisions that were made for you.

In this course, we’ll be covering three broad categories of decisions that can be encapsulated in a component: state, view, and logic. Each of these 3 categories can be internal and hidden from the parent component or exposed and controlled by the parent component.

This course will explore various techniques for moving an Angular component from completely static to very configurable. A good rule to follow is to choose the simplest pattern that meets your needs, and only refactor as you feel the pain points that require a more complex pattern.

**Comment by MaggieAppleton** [comment]
# Primary Tech – Angular

![angular2](https://user-images.githubusercontent.com/5599295/45313571-255cf080-b527-11e8-861c-211a34efd16e.png)

All about [Angular](https://angular.io)

<hr>

## Main Concept

#### Concept in here

*Keywords:* Components, Parts, 

## Ideas to Start With

* Thing
* Thing

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/a33xkq1y8d82k1i/AAAq1RWevCzSGoz4ML99Yx46a?dl=0
