### ISSUE TITLE
CSS Selectors in Depth

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#134]
# Primary Tag
CSS

https://egghead.io/courses/css-selectors-in-depth

Cascading style sheet (CSS) selectors are the glue that connect styling to HTML content. Understanding how they work enables a developer to write more semantic markup and keeps styling modular for better project maintenance. We are going to start with basic selectors and work our way through more complex classification of selectors explaining common use cases along the way. Finally, we’ll look at how selectors can be combined and how selector specificity can create some common problems.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/v6oj0fay5kew3pi/AAARfeaEOTVdAvQoBDL_HTT1a?dl=0
