### ISSUE TITLE
Execute npm Package Binaries with the npx Package Runner

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#139]
Primary Tag
[npx](https://www.npmjs.com/package/npx) (npm)

In this course we will examine the npx package runner and look through various scenarios where the tool is helpful when running node packages from the command line. The npx runner opens up the opportunity to test out various versions of a package, run packages without globally installing, running code directly from GitHub, and other helpful features that make working with packages much easier.

**Comment by MaggieAppleton** [comment]
Creative brief written up in Dropbox > [Execute npm Package Binaries with the npx Package Runner](https://paper.dropbox.com/doc/Course-Illustration-Execute-npm-Package-Binaries-with-the-npx-Package-Runner--ANhFw9pI2kPhEwPwuVF6R3KRAQ-5YMG2o3bgGSkXaZuZVHpF)

**Comment by MaggieAppleton** [comment]
# Main Tech – NPX & NPM


### Course link: (Pending)

### Course Description:
In this course we will examine the npx package runner and look through various scenarios where the tool is helpful when running node packages from the command line. The npx runner opens up the opportunity to test out various versions of a package, run packages without globally installing, running code directly from GitHub, and other helpful features that make working with packages much easier.

<hr>

### Previous Javascript Illustrations
<img width="900" alt="image" src="https://user-images.githubusercontent.com/5599295/45944933-cf3a8380-bfe3-11e8-90a3-52359f743435.png">

## Keywords:

* NPM, packages, package manager, installing, nodes, delivering packages.
Expanded features, extra tools, power up, extension, 

<hr>

## Ideas to Start With:
- An NPM toolkit with a central NPX spanner/hammer/screwdriver/etc. sticking out of the front. 
- Mail packages travelling along an NPM line in a square/ flat 2D dimension. And then a second layer of packages travelling along an NPX line in 3D / curved / dynamic dimension. 
- An NPX booster pack attached onto an NPM vehicle.
-

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/k4yluorqlwez33u/AABKK0aLSqs-fTn78Kbh5iu5a?dl=0
