### ISSUE TITLE
JavaScript Promises in Depth

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#140]
# Primary Tag
JavaScript

https://egghead.io/courses/javascript-promises-in-depth

ES2015 brought a native Promise to the JavaScript standard library. In this course, we’re going to take an in-depth look at how to use promises to model various kinds of asynchronous operations.

First, we’re going to explore how to create promises using the Promise constructor or the Promise.resolve() or Promise.reject() methods. Then, we’re going to see how to chain promises together using .then(), .catch(), and .finally(). We’re going to compare various error handling strategies along the way. We’re going to wrap up this course by taking a look at how to deal with multiple promises using Promise.all() and Promise.race() and how to await a promise using the await operator.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/lj4lfvbuevk8d75/AABZOGPUmYCu0Gkyd2BPB1N9a?dl=0
