### ISSUE TITLE
Asynchronous JavaScript with async/await

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-design#15]
https://egghead.io/courses/asynchronous-javascript-with-async-await

**Comment by trevordmiller** [comment]
The instructor just finished this course and I've reviewed and approved it. It should be ready to go once course artwork is ready.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/9atp71vj02ynrm9/AABOTekMkveQcuhygl4c4ndpa?dl=0
