### ISSUE TITLE
Add Internationalization (i18n) to a React app using React Intl

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#29]
https://egghead.io/courses/add-internationalization-i18n-to-a-react-app-using-react-intl

This course add's [internationalization](https://github.com/yahoo/react-intl) to a react  app that provides 'an API to format dates, numbers, and strings, including pluralization and handling translations.'

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/ed5f6qckoucmmp9/AADMYcyF9aefmuTDv7PrlKvka?dl=0
