### ISSUE TITLE
Understand How to Style Angular Components

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#30]
"In this course we will take a deep dive into the various possibilities Angular offers for styling components. We learn about the different APIs, how they allow us to conditionally apply one or multiple styles in the form of style attributes and CSS classes. We also explore the concept of style encapsulation and how it helps prevent our styles from leaking into other components."

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/q69g6uz2d3fya99/AACK8EQvUjkGkt0EU5KfAb6la?dl=0
