### ISSUE TITLE
Use TypeScript to Develop Vue.js Web Applications

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#34]
https://egghead.io/courses/use-typescript-to-develop-vue-js-web-applications

TypeScript is a powerful JavaScript superset which brings you first-class static type-checking along with latest ECMA Script features. Vue is one of the most modern libraries for managing the view layer.
Angular has fully adopted TypeScript as its language, and React has broad support for it. But, what about Vue?
This course will show how to take full advantage of TypeScript static typing on Vue apps by using class based components, typing directives and using decorators.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/pu3vz87oz953hnl/AABZc91Fk5LIQljnhHx7sAT9a?dl=0
