### ISSUE TITLE
Build A React App With Redux

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#36]
https://egghead.io/courses/build-a-react-app-with-redux

Managing state in modern web applications is hard. As applications grows in complexity, keeping track of state changes and mapping those changes back to your UI becomes increasingly difficult.
One way data flow makes managing state more approachable and lightens the cognitive load required to follow the flow of data through your application. Using Redux takes this idea to the next level and moves the state and the state changes and centralizes them in a global store, managed with pure reducer functions.
In this course you will learn how to build a production quality React application using Redux. We will build up from using redux by itself, so we can understand the core API and how that interacts with a React application, then we’ll move on to introduce react-redux to abstract away some of the underlying details and clean up our code. We’ll use middleware and a mocked API server to understand how asynchronous code fits into the Redux model and we’ll even deploy our finished work so we can see it running live in the cloud.
If you are brand new to React, you’ll want to read the documentation and watch our free React Fundamentals course and our Build Your First Production Quality React App course. To get up to speed on Redux, you should check out Dan Abramov’s Getting Started With Redux course.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/bx4ct5nplzk9i9x/AABYEHZNYR6JQFyOINRz8irca?dl=0
