### ISSUE TITLE
Build Virtual Reality Experiences Using React VR

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#37]
https://egghead.io/courses/build-virtual-reality-experiences-using-react-vr

In this course we will explore the possibilities to bring VR to the Web using React VR. Each lesson focuses on one specific concept or component that comes with React VR. This guide covers a large surface area of experiences like teleporting a user to a recorded 360° experience as well as placing them in virtual worlds. Even a combination of both is possible. Each lesson is independent, but some require knowledge explained in a previous lesson.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/0njtebb3aqdxpiz/AABmVZ3FimXaddNzWQIEryUva?dl=0
