### ISSUE TITLE
Write type-safe Vuex stores with TypeScript

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#38]
https://egghead.io/courses/write-type-safe-vuex-stores-with-typescript

In Use TypeScript to Develop Vue.js Web Applications we’ve seen how TypeScript Vue apps development by creating class based components and using decorators.
This course will extend it, showing you how you can use Vuex with TypeScript in order to manage the state of your Vue app. We’ll see how to type-safe your store, organize the state in modules, modify it using mutations and actions and write Vuex plugins, all by creating a beer shop app throughout the course.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/vct3pdapr5lcp60/AADIxMqw_N56rRITAxMGgDfPa?dl=0
