### ISSUE TITLE
Intro to Python

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#39]
https://egghead.io/courses/intro-to-python

In Introduction to Python, we will start at the beginning: Installing python 3 and using virtual environments. With a working environment, we will learn how to manipulate strings and numbers, and gain working knowledge of data structures and flow control. We will build on that by introducing modules and classes and learn how to interact with our python applications using command line switches, console input and files.
At the end of this course, you’ll have a great working knowledge of Python, fully capable of creating your own Python projects from scratch or jumping into an existing application with the capability to read, understand, and contribute to the application.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/4cvj67k49ebsafx/AABoqX9m7HoInNkUGILgxGI6a?dl=0
