### ISSUE TITLE
Maintainable CSS using TypeStyle

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-design#4]
https://egghead.io/courses/maintainable-css-using-typestyle

https://github.com/typestyle/typestyle

An extension of https://www.typescriptlang.org/ for styles in JavaScript

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/41jm0168kqwa7rj/AADJwrB3giElc4bPVdZxKmtda?dl=0
