### ISSUE TITLE
Cycle.js Fundamentals

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#40]
This is an older course that just got a full update. One big thing to note is that the library is no longer build on RxJS. We are going to re-release this course a new 

Cycle.js is a framework where your app is described as a simple function taking an event stream as input and outputting an event stream.

https://cycle.js.org/

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/joz5wl1fk2r6wfr/AAC91nevTd5Q8mPPysjutDXDa?dl=0
