### ISSUE TITLE
Understand the Elm Type System

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#41]
[Understand the Elm Type System](https://egghead.io/courses/understand-the-elm-type-system)

Elm has a powerful type system that can help you to model your application's data precisely and safely. This course will introduce you to the various types available, and teach you when and how to use each one.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/q4d0k0xs8u6xua4/AAAOZaq4ws-V23OpnIynd8RRa?dl=0
