### ISSUE TITLE
Create a News App with Vue.js and Nuxt

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#43]
https://egghead.io/courses/create-a-news-app-with-vue-js-and-nuxt

This course walks you through the steps of creating a News web app using Vue.js and the Nuxt framework. You will learn how to create dynamic pages for each section of your application and load, store, display, filter, and style the data. Then end result will be a News app with multiple category pages, comments for each section, and user pages.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/64ohmy4p15tycx4/AACO_uQ8KhapppGbKfnYYS4Ta?dl=0
