### ISSUE TITLE
Learn HTTP in Angular

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#44]
https://egghead.io/courses/learn-http-in-angular

Client-server communication is at the heart of any modern web application. In this course we will take a look at how to communicate with your backend API in Angular, specifically with the new Http module introduced in version 4.3.1. We will learn how to configure the HttpClientModule, how to fetch and send data, customize HTTP headers that are being sent and how to properly handle error responses. We will also take a look at some more advanced use cases such as listening to progress events and intercepting HTTP calls. Finally we will also learn how to isolate and mock HTTP calls in automated unit tests.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/avgkjq5rn2lyk74/AABUw8XOWO1NX2GEfyvYju6ba?dl=0
