### ISSUE TITLE
Advanced Types in TypeScript

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#45]
https://egghead.io/courses/advanced-typescript

This course explores the capabilities of TypeScript’s type system in depth. It illustrates powerful features of the type system and shows how to apply them in practice.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/txxubxnngv67iue/AABUncL7_S_M0Q1HQ4oXTi5ca?dl=0
