### ISSUE TITLE
Video Upload

### ISSUE THREAD

**Issue by vojtaholik** [eggheadio/egghead-design#46]
# Illustration for our Video Upload 
⚙️ https://egghead.invisionapp.com/share/XTDEQWQ5H

## 💻 Occurs on
Creating and Editing Lesson
https://egghead.invisionapp.com/share/JNBDSMAHR#/229954279_-_Creating_and_Editing_Lessons

## 👎 Currently
![video upload](https://user-images.githubusercontent.com/25487857/30281838-ceceddf0-9713-11e7-956c-3d131a549a01.png)

## 🖼 Specs
bg: light
size: the video upload component content container size is 680x410 (https://cl.ly/mSEn) and we need to fit an illu, browse button and one line of text (info about file type etc) within it. So you could pick multiple ratios to work with and it’s all good as far as the content inside fits. Even like this - https://cl.ly/mSRm

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/3p15v1nb5ou95dc/AAD_FlwMUCBk_PWxOw_LXQROa?dl=0
