### ISSUE TITLE
Email Confirmation Landing

### ISSUE THREAD

**Issue by vojtaholik** [eggheadio/egghead-design#47]
# Illustration as a "Thank you for subscribing to updates!" 

## 💻  Occurs on
Opt-in Landing - https://egghead.invisionapp.com/share/9PDFDPUUG

## 👎 Currently
![emails](https://user-images.githubusercontent.com/25487857/30282389-771decac-9715-11e7-901c-988001d17905.png)

## 🖼  Specs
bg: dark
size: around _it's up to you_ px

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/cta85676u0l71eu/AAAHmAtjrspenJ5hpMbo5TAxa?dl=0
