### ISSUE TITLE
Enhanced Transcript

### ISSUE THREAD

**Issue by vojtaholik** [eggheadio/egghead-design#48]
# Smaller illustration representing enhanced transcript availability on lesson page.

## 💻  Occurs on
Transcript ⚙️  https://egghead.invisionapp.com/share/85DFWGZ2U
Lesson Watching page https://egghead.invisionapp.com/d/main/#/projects/prototypes/10399246

## 👎 Currently
![image](https://user-images.githubusercontent.com/25487857/30282750-7c591934-9716-11e7-9de3-da0d53d1186f.png)

## 🖼  Specs
bg: light
size: around 150x150px

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/l75f05xjlc8gpb9/AADB7r559gKMpD4_M4KjRBl-a?dl=0
