### ISSUE TITLE
 Higher Order Components with Functional Patterns Using Recompose

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-design#5]
I think we could recycle a runner up from previous react course for this? :)

Feel free to go nuts though.

https://egghead.io/courses/using-functional-patterns-in-react-using-recompose

https://github.com/acdlite/recompose

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/lnhi1oe57kuv8dr/AAC6-6lRFo9a1a04u7zorWsaa?dl=0
