### ISSUE TITLE
Community Resource badge

### ISSUE THREAD

**Issue by vojtaholik** [eggheadio/egghead-design#50]
# Community Resource icon/badge
known also as _"free but not cheap"_ or as Joel noted _"We want to shout it from the rooftops, but in the classiest way we can. THIS IS FOR YOU DEAR FRIENDS OF OPEN SOURCE!"_

## 💻  On page
Course detail: https://egghead.invisionapp.com/share/WTAH6QMD2#/219261652_1-1-1-Course
We might use it on Lesson watching page too:
![image](https://user-images.githubusercontent.com/25487857/30318661-01c21926-97ae-11e7-8c67-adfc23594073.png)
Or in Content List:
![image](https://user-images.githubusercontent.com/25487857/30318510-9bc36346-97ad-11e7-9755-bdbb3d8e597c.png)

## 👎  Currently
![image](https://user-images.githubusercontent.com/25487857/30318706-2336fb8a-97ae-11e7-8dc9-956044f47e48.png)
(I'll adjust the container itself when applying new illu)

## 🖼  Specs
1:1 ratio
I can imagine using this badge in either small sizes (24x24px, in content list component), medium (56x56px, on course page) and big (basically anything bigger than 64x64px). The small size (24) can be tricky and won't be used at least for a while now (I could also badge a list row somehow differently), so I'd say we can skip it for now if it won't work.

When I think about "Achievement Badges" on User's Dashboard (future task), "Community Resource" might probably be one of them and serve as a good starting point? 🤔

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/93glwkpfd3xnisn/AABMRM382J27h2VZgVB6M_qea?dl=0
