### ISSUE TITLE
Leverage New Features of React 16

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#59]
https://egghead.io/courses/leverage-new-features-of-react-16

In this course we will explore the new features coming with React 16. Each lesson explains each new feature at a time.

The lessons not only explain the new technical capabilities, but also go into the recommended practices.

After watching this course you will be ready to leverage everything available in React 16.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/q6f33x035ya7v3t/AABe8O4HstNI5ocSGxc5EZTva?dl=0
