### ISSUE TITLE
Quickly Transform Data with Transducers

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#64]
In this course we will go through the concept of transducers and build them up from basic principles. We will go over the problems with regular composed transformations, and show how we end up with unnecessary data and intermediate collections. We go on to learn how we can use transducers for performance gains when operating on large data sets, as well as how they’re a great fit for processing other iterable data, like streams. Not just arrays.

https://egghead.io/courses/quickly-transform-data-with-transducers

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/65hoau8mlqcyts5/AACMWUSbxvSz-4s5kmnwRIbZa?dl=0
