### ISSUE TITLE
Build a Twelve-Factor Node.js App with Docker

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#66]
In this course we will take a simple Node.js app that connects to a MongoDB database and uses an Express web server, and learn how to setup a full software development deployment process as well as how to properly “Dockerize” the app. We’ll step through setting up proper version control techniques, managing configuring within the environment, setting up proper build/deploy/run processes, and all with abiding by Docker best practices. We’ll also make sure our deployment is setup for scale, and have consistent development practices in place for reliable app deployments.

https://egghead.io/courses/build-a-twelve-factor-node-js-app-with-docker

**Comment by MaggieAppleton** [comment]
Assigned to Kamil

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/3ypy9wo2izk5f2o/AABwkO7Frkzr1UCORpkwAZK2a?dl=0
