### ISSUE TITLE
Make Webpack Easy with Poi

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#67]
When setting up a modern JavaScript app, we find ourselves trudging through the land of infinite configuration. Poi offers us an option of zero-configuration by providing sane defaults and hiding them away until you need to tweak a change to suit your needs.

https://egghead.io/courses/make-webpack-easy-with-poi

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/pt4rugjzwjuqjj5/AACvl6yYkRonZmXujjYChALha?dl=0
