### ISSUE TITLE
Build a Blog with React and Markdown using Gatsby

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#68]
A large part of a software developer’s time is spent searching the internet for answers to a never-ending stream of questions. Often, the answers we find are on blogs written by people who’ve been there, and found a solution. Isn’t it time you paid it forward?

Gatsby.js is a static site generator for React with a plugin ecosystem that makes it super easy to publish.

In this course, you’ll build a Gatsby site that transforms Markdown documents from your local filesystem into HTML. From there, you’ll use GraphQL to query posts for displaying on an index page, link between posts, and group posts by tags. After your site has been compiled, you’ll see how to deploy it via Github Pages or Amazon AWS.

https://egghead.io/courses/build-a-blog-with-react-and-markdown-using-gatsby

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/v2tmlvrucq2mt6f/AAAoopqZfTHmBS9ho69eiGLQa?dl=0
