### ISSUE TITLE
Create Dynamic Forms in Angular

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#69]
https://egghead.io/courses/create-dynamic-forms-in-angular

Angular forms are extremely powerful and cope with a lot of different use cases. But apart from basics such as binding data to an HTML form, applying validation and gathering the user input, there are more advanced use cases. One of them is to be able to dynamically render the HTML form based on some metadata object which could either be constructed on your client-side application or even be exposed by some API on your backend server.

Dynamic forms are great because they may help you reduce costs by automating a large number of forms to be rendered and at the same time you’re able to react much quicker to changing business or regulatory requirements. In this course we will use Angular’s Reactive Forms and learn about the basics for dynamically rendering FormControls and even bind more advanced input controls such as select boxes and radio button lists. If you’re coming from AngularJS (v1.x) you may also be familiar with dynamic forms in the context of Formly, a library for automating dynamic forms. We will also quickly touch on ng-formly, which is the Angular (2+) equivalent.

**Comment by MaggieAppleton** [comment]
Assigned to Vojta

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/1ssnhej46p7b0jy/AAD7tAs9Ju_R6hRA_ckBNorqa?dl=0
