### ISSUE TITLE
Build a Server Rendered + Code Split App in React with React Universal Component

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#74]
https://egghead.io/courses/build-a-server-rendered-code-split-app-in-react-with-react-universal-component

In this course, you will be learn how to get your react app to load as quickly as possible to maximize user engagement—we need faster rendering speed and smaller network requests!

You’ll learn how to both split code into lazily loaded bundles AND server-side render your page.

This has not been possible until very recently—you had to choose either code-splitting or SSR. Sure you have Next.js which is awesome, but it’s a framework that you need to buy into. With react-universal-component you are getting a framework-less Next.js that is in your control!

The react-universal-component library does a great job making it as simple as can be, but there are still various specific configurations and practices that must be followed to get it working. So watch the videos to learn how it’s done!

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/yr12bf9uc7ckrz2/AAATEVz2dnktDcVvE6doriBga?dl=0
