### ISSUE TITLE
Create Dynamic Components in Angular

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#76]
https://egghead.io/courses/create-dynamic-components-in-angular

Angular is extremely powerful. Even with it’s basic constructs you can come up with sophisticated applications. However, once you master the basics, it’s important to dive into some more advanced topics which will help you leverage the true power of Angular even more. In this lesson we’re taking the specific use case of of creating a tabbed component which allows us to dynamically define new tabs. On our journey of implementing this component we will learn about how we can dynamically instantiate components, leveraging the ComponentFactoryResolver and ViewContainerRef. Furthermore we will explore how to define view templates, how to pass them to our dynamically instantiated components as well as how to pass data into those templates. All of this will be powered by ngTemplateOutlet and ngTemplateOutletContext.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/5qozkrtzvgrykf7/AACcmC9EGIOBIABRBwdNihBna?dl=0
