### ISSUE TITLE
Introductory Machine Learning in Python with scikit-learn

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#77]
https://egghead.io/courses/introductory-machine-learning-in-python-with-scikit-learn

In this course we’ll learn about common machine learning algorithms, particularly those that don’t require implementing a neural network. We’ll implement these in Python using scikit-learn using scikit-learn’s inbuilt data sets.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/mmpjqz6in6ql12m/AAAXoeB3_CVGUMbw-5r0GBCXa?dl=0
