### ISSUE TITLE
Manage Application State with Mobx-state-tree

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#78]
https://egghead.io/courses/manage-application-state-with-mobx-state-tree

In this course we will build a little bookshop application using React, Mobx-state-tree (MST) and create-react-app. You will learn how to model your application state after your problem domain. You will be able to manage the lifecycle of your data by describing data models. Models are like React components, but then for data! Finally you will see that MST allows you to solve certain problems generically by leveraging it's out of the box support for asynchronous actions, patches, snapshots and middleware.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/s/96v37mkk3v6ynwy/Screenshot%202017-11-29%2016.45.28.png?dl=0
