### ISSUE TITLE
Understand JavaScript's this Keyword in Depth

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#79]
https://egghead.io/courses/understand-javascript-s-this-keyword-in-depth

JavaScript’s this keyword is a source of confusion for many developers. It can be frustrating if, for some reason, this doesn’t point to the context that was intended. This course will help you understand JavaScript’s this mechanism in depth.

We’ll see that the call-site of a function determines the this value of that function invocation. We’ll also learn how to call a function with a specific this value and how to create functions that always remain tied to a specific this context. Finally, we’ll take a look at how this is treated within arrow functions and classes.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/s/az4tt5nqiy5hhqa/Screenshot%202017-12-04%2013.37.56.png?dl=0
