### ISSUE TITLE
Async Programming: End of the Loop

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-design#8]
https://egghead.io/courses/mastering-asynchronous-programming-the-end-of-the-loop

This is a very gentle and awesome introduction to async coding in JS.

async, no loops, rxjs, streams, functional, observable, arrays

**Comment by MaggieAppleton** [comment]
Finished by Maxime.
Final files:
https://www.dropbox.com/sh/e0a0bbxve7auj8m/AAAj_FYST6dNmqS1Um19pMwKa?dl=0
