### ISSUE TITLE
SEO Friendly Progressive Web Applications with Angular Universal

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#80]
https://egghead.io/courses/seo-friendly-progressive-web-applications-with-angular-universal

In this course we will create an Angular application that will serve as a public website. Normally there are quite a few trade-offs by using a Single Page Application for a public website. For instance, they are hard to index by search engines and if you link to them on social media you get a generic preview. Also, the initial rendering can take a while (especially on mobile devices) as the browser has to pull in all the JavaScript in order to render a working app.

By adding and configuring Angular Universal we add Server Side Rendering capabilities to our application. This helps prevent the issues mentioned above by pre-rendering the application on the server and serving this out to the user when she requests the app. Once the JavaScript has been loaded the app will seamlessly switch over to a ‘normal’ web application.

For good measures and to modernize our application we will add and configure a Service Worker that will allow for a native-like experience in the browser (splash screen, desktop icon, fast load, cached data, etc).

**Comment by MaggieAppleton** [comment]
Assigned to Maxime

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/2uxi7mpxmuzk0bs/AAB-lEpbfM2y7Ep_2-EPxyh_a?dl=0
