### ISSUE TITLE
Async/Await using TypeScript

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#86]
https://egghead.io/courses/async-await-using-typescript

Mastering asynchronous code execution is fundamental to becoming a great TypeScript developer. In this course we show how TypeScript enables you to write asynchronous code with complete type safety and great runtime support thanks TypeScript’s understanding of the async / await pattern.

In this course we will cover concepts like Promises, generators and how they enable the runtime environment to allow authoring asynchronous code just as beautifully as synchronous code.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/ftq2rliz1qx93qb/AAD_aWdSsHxeHWznMTSnBWXva?dl=0
