### ISSUE TITLE
Form Validation in Elm

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#87]
https://egghead.io/courses/form-validation-in-elm

Validating forms can be quite a challenge. You not only need to write the logic for validation, but also keep track of the user's interaction with the form, to ensure a smooth user experience. If you've decided that the browsers' constraint validation is not for you, then this course teaches you how to perform validation using pure Elm code. In the process, we will touch upon several Functional Programming techniques that come in handy

As a starting point, we take the simple contact form built in my course on the Elm Architecture. This course assumes you are familiar with the basics of the Elm Architecture and the Elm type system.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/s/vaxq88qj6yda0mi/Screenshot%202018-01-31%2010.39.31.png?dl=0
