### ISSUE TITLE
Learn the Elm Architecture by Building a Simple Form

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#88]
https://egghead.io/courses/learn-the-elm-architecture-by-building-a-simple-form

Building a simple form is a great way to familiarize yourself with the Elm Architecture. Forms present several challenges: data binding, user interaction, and server interaction. This complexity is why building forms can be a difficult task! The ideas and techniques presented in this course will give you a solid foundation to start building forms of arbitrary complexity with Elm.

This course does not assume previous familiarity with the Elm Architecture. It does assume some basic knowledge of the Elm language. If you have not done so before, consider watching this 7-minute introduction to Elm and my course on the Elm type system.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/m11ks70hb9k9zkh/AADRDolsXHLzZlIIE4EWyC7ma?dl=0
