### ISSUE TITLE
Structure Angular Apps with Angular Material Components

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#89]
https://egghead.io/courses/structure-angular-apps-with-angular-material-components

In this course we will explore the major Angular Material components. We will start with components related to navigation, layout, and structure, building out an application shell while demonstrating each component’s API and common use-cases. We will then move through the utility, form, and datatable components, demonstrating how each can be used to suit your project’s needs. Finally we will touch on theming your application to create a custom look and feel that fits within the Material Design guidelines.

By the end of this course you will be comfortable leveraging the Material Design library to structure your next Angular application, creating an awesome user experience!

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/t1seig892eckjeb/AACrKjCPseqhaUoLC1SAG2Hfa?dl=0
