### ISSUE TITLE
How to Write an Open Source JavaScript Library

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-design#9]
https://egghead.io/courses/how-to-write-an-open-source-javascript-library

This is a beginner's guide to publishing open source libraries. 

Tools used: Github, npm, TravisCI, mocha, babel

getting started, effective system, creation, tested, publish, create, contributor

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/tkkfbti5crd9tqq/AACWHBflgHUhiX00ZCe64iJXa?dl=0
