### ISSUE TITLE
Build a Server-rendered ReactJS Application with Next.js

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#91]
https://egghead.io/courses/build-a-server-rendered-reactjs-application-with-next-js

In this course we we’ll see just how quickly next.js makes the process of building server-rendered ReactJS applications by creating and deploying an application that loads blog posts from the Google Blogger API. Along the way we’ll learn about many of the amazing features Next.js provides for us out of the box, such as route prefetching and code-splitting, thus allowing us to spend more time developing and virtually no time setting up our environment.

Additionally, we’ll learn about the core concepts behind the framework and see how we can leverage them to create dynamic routes and integrate Material-UI on the server. We won’t have to worry about using any specific architecture to handle state, instead we will just pass our data as ReactJS props using Next.js’ getInitialProps lifecycle hook. Throughout this course we will see why Next.js has gained such an amazing reputation as a “minimalist framework” by supplying users with “pretty” error messages. Once finished, we’ll deploy our application to a live URL using the now-cli npm module.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/zyv3o2r28k17umx/AAAd9q-zri4reM7UlPr22w_ha?dl=0
