### ISSUE TITLE
Build User Interfaces by Composing CSS Utility Classes with Tailwind

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#96]
In this course, we learn how to make the most out of Tailwind’s JavaScript configuration file and custom PostCSS functions and directives.

We learn how to compose utility classes to build custom user interfaces, and we discover how to generate utility classes that target specific breakpoints and states.

By the end of the course, you should have a firm understanding of how Tailwind works and be able to create your own tailor-made design system and utility class CSS toolkit for your next project!

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/sh/va62y3b290t7d5q/AAC3Y-VEW46FeySzYmJ_CFFla?dl=0
