### ISSUE TITLE
Decode JSON into Elm

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-design#98]
https://egghead.io/courses/decode-json-into-elm

Any non-trivial Elm app will have a need to translate between JSON and Elm, as the Elm app communicates with JavaScript libraries through ports, or consumes JSON from a server API. Elm has the important and somewhat intimidating concept of "decoders" that translate dynamically typed JSON into statically typed Elm values. This course will teach you to write your decoders and tackle many common decoding scenarios, including optional and nullable fields, decoding into union types, and decoding recursive structures.

**Comment by MaggieAppleton** [comment]
https://www.dropbox.com/s/ms0e81wkqbzp4ex/Screenshot%202018-02-06%2016.15.25.png?dl=0
